# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.cache/wt [current_project]
set_property parent.project_path C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter.dcp
set_property used_in_implementation false [get_files c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fp_adder_subtracter/fp_adder_subtracter.dcp]
add_files -quiet c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fifo/fifo.dcp
set_property used_in_implementation false [get_files c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fifo/fifo.dcp]
add_files -quiet c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fp_greater_than/fp_greater_than.dcp
set_property used_in_implementation false [get_files c:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/ip/fp_greater_than/fp_greater_than.dcp]
read_vhdl -library xil_defaultlib {
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/threshold_exceeding_detector.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/fp_max.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/fp_rom256x32.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/cumulative_sums_detector.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/mpg.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/display_7seg.vhd
  C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/sources_1/new/basys3_cusum_anomaly_detector.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/constrs_1/imports/Downloads/Basys3_test_env.xdc
set_property used_in_implementation false [get_files C:/CTI/Licenta/cumulative_sums_anomaly_detection/cumulative_sums_anomaly_detection.srcs/constrs_1/imports/Downloads/Basys3_test_env.xdc]


synth_design -top basys3_cusum_anomaly_detector -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basys3_cusum_anomaly_detector.dcp

catch { report_utilization -file basys3_cusum_anomaly_detector_utilization_synth.rpt -pb basys3_cusum_anomaly_detector_utilization_synth.pb }
